User_profile_app/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include

from django.conf import settings
from django.conf.urls.static import static

from . import views

urlpatterns = [
                  path('admin/', admin.site.urls),
                  url(r'^accounts/', include(('accounts.urls', 'accounts'),
                                             namespace='accounts')),
                  url(r'^$', views.home, name='home'),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'sign_in/$', views.sign_in, name='sign_in'),
    url(r'sign_up/$', views.sign_up, name='sign_up'),
    url(r'sign_out/$', views.sign_out, name='sign_out'),
    url(r'profile/$', views.profile, name='profile'),
    url(r'profile/edit/$', views.edit_profile, name='edit'),
    url(r'profile/change_password/$', views.change_password,
        name='change_password'),
]

accounts/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.core import validators

User = get_user_model()


class Profile(models.Model):
    user = models.OneToOneField(
        User,
        on_delete=models.CASCADE,
        primary_key=True

    )
    first_name = models.CharField(max_length=255, blank=True, default='')
    last_name = models.CharField(max_length=255, blank=True, default='')
    email = models.EmailField(blank=True, default='please_change@hotmail.com')
    date_of_birth = models.DateField(blank=True, default='1990-01-01')
    bio = models.CharField(max_length=255, default='please change', blank=True,
                           validators=[validators.MinLengthValidator(10)])
    avatar = models.ImageField(blank=True, null=True,
                               upload_to='test/')

accounts/forms.py
from django import forms
from . import models


class EditForm(forms.ModelForm):
    class Meta:
        model = models.Profile
        fields = [
            'first_name', 'last_name',
            'email', 'date_of_birth', 'bio', 'avatar'
        ]


class EditFormWithValidation(EditForm):
    confirm_email = forms.EmailField()

    def clean(self):
        cleaned_data = super(EditForm, self).clean()
        email = cleaned_data.get("email")
        confirm_email = cleaned_data.get("confirm_email")

        if email and confirm_email:
            if email != confirm_email:
                raise forms.ValidationError("Emails do not match.")

        return cleaned_data

    class Meta(EditForm.Meta):
        fields = EditForm.Meta.fields + ['confirm_email']

User_profile_app/views.py
from django.shortcuts import render


def home(request):
    return render(request, 'home.html')

accounts/views.py
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, \
    PasswordChangeForm
from django.urls import reverse
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.decorators import login_required
from . import models, forms


def sign_in(request):
    """  form to sign in the user """
    form = AuthenticationForm()
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            if form.user_cache is not None:
                user = form.user_cache
                if user.is_active:
                    login(request, user)
                    return HttpResponseRedirect(
                        reverse('accounts:profile')
                    )
                else:
                    messages.error(
                        request,
                        "That user account has been disabled."
                    )
            else:
                messages.error(
                    request,
                    "Username or password is incorrect."
                )
    return render(request, 'accounts/sign_in.html', {'form': form})


def sign_up(request):
    """to create user from sign up form """
    form = UserCreationForm()
    if request.method == 'POST':
        form = UserCreationForm(data=request.POST)
        if form.is_valid():
            form.save()
            user = authenticate(
                username=form.cleaned_data['username'],
                password=form.cleaned_data['password1']
            )
            login(request, user)
            profile = models.Profile()
            profile.first_name = form.cleaned_data['username']
            profile.user = request.user
            profile.save()
            messages.success(
                request,
                "You're now a user! You've been signed in, too."
            )

            return HttpResponseRedirect(reverse('accounts:profile'))
    return render(request, 'accounts/sign_up.html', {'form': form})


@login_required
def sign_out(request):
    """signs out user """
    logout(request)
    messages.success(request, "You've been signed out. Come back soon!")
    return HttpResponseRedirect(reverse('home'))


@login_required
def profile(request):
    """ displays users profile """
    profile = get_object_or_404(models.Profile, pk=request.user.id)
    return render(request, 'profile.html', {'profile': profile})


@login_required
def edit_profile(request):
    """displays form to edit user profile detials"""
    profile = get_object_or_404(models.Profile, pk=request.user.id)
    form = forms.EditFormWithValidation(instance=profile)

    if request.method == 'POST':
        form = forms.EditFormWithValidation(request.POST, request.FILES,
                                            instance=profile)
        if form.is_valid():
            form.save()
            messages.success(request,
                             "Updated {}'s profile".format(
                                 form.cleaned_data['first_name']))
            request.user.first_name = form.cleaned_data['first_name']
            request.user.last_name = form.cleaned_data['last_name']
            request.user.email = form.cleaned_data['email']
            request.user.save()
            return HttpResponseRedirect(reverse('accounts:profile'))
    return render(request, 'edit.html',
                  {'form': form, 'profile': profile})


@login_required
def change_password(request):
    """displays form to change password """
    form = PasswordChangeForm(user=request.user)
    if request.method == 'POST':
        form = PasswordChangeForm(data=request.POST, user=request.user)
        if form.is_valid():
            form.save()
            messages.success(
                request,
                "Password has been changed and you have been"
                " logged out for security purposes"
            )

            return HttpResponseRedirect(reverse('home'))
    return render(request, 'accounts/change_password.html', {'form': form})

accounts/templates/accounts/sign_in.html
{% extends "layout.html" %}

{% block title %}Sign In | {{ super }}{% endblock %}

{% block body %}
<form method="POST" action="{% url 'accounts:sign_in' %}">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" class="button-primary" value="Sign In">
</form>
{% endblock %}

accounts/templates/accounts/sign_up.html
{% extends "layout.html" %}

{% block title %}Sign Up | {{ super }}{% endblock %}

{% block body %}
<form method="POST" action="{% url 'accounts:sign_up' %}">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" class="button-primary" value="Sign Up">
</form>
{% endblock %}

templates/accounts/change_password.html
{% extends "layout.html" %}

{% block title %}Sign In | {{ super }}{% endblock %}

{% block body %}
<form method="POST" action="{% url 'accounts:change_password' %}">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" class="button-primary" value="change password">
</form>
{% endblock %}

templates/accounts/sign_in.html
{% extends "layout.html" %}

{% block title %}Sign In | {{ super }}{% endblock %}

{% block body %}
<form method="POST" action="{% url 'accounts:sign_in' %}">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" class="button-primary" value="Sign In">
</form>
{% endblock %}

templates/accounts/sign_up.html
{% extends "layout.html" %}

{% block title %}Sign Up | {{ super }}{% endblock %}

{% block body %}
<form method="POST" action="{% url 'accounts:sign_up' %}">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" class="button-primary" value="Sign Up">
</form>
{% endblock %}

templates/bio.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

templates/edit.html
{% extends 'layout.html' %}
{% block body %}
<div class="row columns">

    <h1>{{ form.instance.first_name|pluralize }} profile</h1>
    <form method="POST" action="" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" class="button" value="Save">
    </form>
</div>
{% endblock %}

templates/home.html
{% extends 'layout.html' %}
{% block body %}
    <div class="grid-100">
        <h1 align="center">Homepage</h1>
        <p align="center">Welcome to my user profile application<br/>
            click sign up to be given a profile you can edit or if you have a
            user account click sign in</p>
    </div>
{% endblock %}

templates/layout.html
{% load static from staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>

    <!-- Basic Page Needs
    –––––––––––––––––––––––––––––––––––––––––––––––––– -->
    <meta charset="utf-8">
    <title>{% block title %}Circle{% endblock %}</title>

    <!-- Mobile Specific Metas
    –––––––––––––––––––––––––––––––––––––––––––––––––– -->
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- FONTS
    –––––––––––––––––––––––––––––––––––––––––––––––––– -->
    <link href='https://fonts.googleapis.com/css?family=Work+Sans:400,500'
          rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Cousine'
          rel='stylesheet' type='text/css'>

    <!-- CSS
    –––––––––––––––––––––––––––––––––––––––––––––––––– -->
    <link rel="stylesheet" href="{% static "css/global.css" %}">

    <!-- JS
    –––––––––––––––––––––––––––––––––––––––––––––––––– -->
    <script type="text/javascript"
            src="https://code.jquery.com/jquery-2.2.0.min.js"></script>
    <script type="text/javascript"
            src="{% static "js/autogrow.js" %}"></script>
    <script type="text/javascript" src="{% static "js/global.js" %}"></script>


</head>
<body>
<header class="circle--header">
    <div class="bounds">
        <div class="circle--fluid">
            <div class="circle--fluid--cell">
                <h1 class="hide-text circle--logo"><a class="logo"
                                                      href="{% url 'home' %}">Circle</a>
                </h1>
            </div>
            <div class="circle--fluid--cell circle--fluid--primary">
                <nav>
                    <ul class="circle--inline--list">
                       {% if not user.is_authenticated %}
                        {% else %}
                            <li><a href="{% url 'accounts:profile' %}">View Profile</a></li>
                        {% endif %}
                    </ul>
                </nav>
            </div>
            <div class="circle--fluid--cell circle--fluid--secondary">
                <nav>
                    <ul class="circle--inline">
                        {% if not user.is_authenticated %}
                            <li><a href="{% url 'accounts:sign_up' %}">Sign Up</a></li>
                            <li><a href="{% url 'accounts:sign_in' %}">Sign
                                In</a></li>
                        {% else %}
                            <!-- view profile link here? -->
                            <!-- edit profile link here? -->
                            <li><a href="{% url 'accounts:sign_out' %}">Sign Out</a></li>
                        {% endif %}
                    </ul>
                </nav>
            </div>
        </div>
    </div>
</header>

<div class="bounds circle--page">
    {% if messages %}
        <ul class="messages centered grid-50">
            {% for message in messages %}
                <li{% if message.tags %}
                    class="{{ message.tags }}"{% endif %}>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}
    {% block body %}{% endblock %}
</div>
</body>
</html>

templates/profile.html
{% extends 'layout.html' %}

{% block body %}
    <div class="grid-100 ">
        <h1> {{ profile.first_name }} {{ profile.last_name }}</h1>
        <div>
            {% if profile.avatar %}
                <img src="{{ profile.avatar.url|default_if_none:'#' }}"
                     width="200" height="200">
            {% endif %}
        </div>
        <div>
            <table>

                <tr>
                    <td class=>email:</td>
                    <td>{{ profile.email }}</td>
                </tr>
                <tr>
                    <td class=>bio:</td>
                    <td>{{ profile.bio }}</td>
                </tr>
                <tr>
                    <td class=>D.O.B:</td>
                    <td>{{ profile.date_of_birth }}</td>
                </tr>


            </table>
        </div>
        <a href="{% url 'accounts:edit' %}">Edit Profile</a>
        <a href="{% url 'accounts:change_password' %}">change password</a>
    </div>
{% endblock %}